[project]
name = "ultimate-tic-tac-toe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tkintertable>=1.3.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
